package com.tarbus.payload.enums;

public enum ERole {
  ROLE_USER,
  ROLE_ADMIN,

  COMPANY_ALL,
  COMPANY_READ,
  COMPANY_UPDATE,
  COMPANY_CREATE,

  COMPANY_USERS_ALL,
  COMPANY_USERS_ADD,
  COMPANY_USERS_REMOVE,

  CHAT_READ_ADMIN_ROOM,
  CHAT_HAS_ADMIN_ROOM,
}
